<?php
/**
 * @copyright 2016 Tungsten Creative
 * @author Oto Hlincik [oh] <oto@me.com>
 * @license Apache (http://www.apache.org/licenses/LICENSE-2.0)
 */

namespace Craft;

/**
 * TungstenVariable provides the Twig variable `craft.tungsten` when inside a
 * Craft template. It is primarily used to link to asset files generated by the
 * Gulp workflow.
 *
 */
class TungstenVariable
{
  /**
   * craft.tungsten.assetUrl() returns a URL that will return the appropriate
   * version of a specified asset file. Only the filename should be specified.
   *
   * @param string $filename  File for which the URL should be returned.
   * @return string           Full URL to the appropriate version of asset file.
   */
  public function assetUrl($filename) {
    $fileSystemPath = craft()->config->get('environmentVariables')['fileSystemPath'];
    $siteUrl = craft()->config->get('environmentVariables')['siteUrl'];
    $appDirPath = $fileSystemPath.'/public/app/';
    $appDirUrl = $siteUrl.'/app/';
    $manifestFilePath = $appDirPath.'rev-manifest.json';
    $assetFilePath = $appDirPath.$filename;

    if (file_exists($manifestFilePath)) {
      // Return the cached version of the asset file
      $manifest = json_decode(file_get_contents($manifestFilePath), true);
      return $appDirUrl.$manifest[$filename];
    }
    else {
      // Return the develoment version of the asset file
      return $appDirUrl.$filename;
    }
  }
}
